### ISSUE TITLE
Sometimes notSaving properly/ Sometimes Cant Use Items.

### ISSUE THREAD

**Issue by yomanmen** [0rangeFox/esx_inventory#1]
Hello, i tried your inventory and i saw that, 
i) Sometimes it doesnt save items on player disconnect so you return with same items as you had last time. It saves both on user table and inventories.
ii) Sometimes you cant use items like water or bread. If i try to buy for example 10 water then i cant use but if i buy 2 i can use. If i cant use water if i drop some of them and pick up again then i can use them dunno why..

Thanks for the share btw..

**Comment by 0rangeFox** [comment]
> Hello, i tried your inventory and i saw that,
> i) Sometimes it doesnt save items on player disconnect so you return with same items as you had last time. It saves both on user table and inventories.
> ii) Sometimes you cant use items like water or bread. If i try to buy for example 10 water then i cant use but if i buy 2 i can use. If i cant use water if i drop some of them and pick up again then i can use them dunno why..
> 
> Thanks for the share btw..

Thanks for replying this message, im gonna release new update in some moment, is about drops too, you are able to see drops like ESX Pickups (Gonna use everything from ESX) and ditched of Disc-base. And after i will gonna work on this problem.

**Comment by yomanmen** [comment]
Hello, very nice update there! But still it doesnt save properly the items you buy from markets etc. Stacking them or not its like it saves the first time some and then its like keeps reseting on my Last saved items! Is this a bug on you too ?
Also i found some typo in your code on [ es_extended\client\modules\marker.lua] Line 80 and 84 you need ESX.UI.Markers not ESX.Markers .
