### ISSUE TITLE
Blip add or dump error.

### ISSUE THREAD

**Issue by shino3v** [0rangeFox/esx_inventory#5]
I removed Createpickupdan dump because of a kind of marker, but I couldn't add it with your help in this issue I think we can fix it please help.

**Comment by sh1noistaken** [comment]
https://streamable.com/gpbxry bug video.

**Comment by 0rangeFox** [comment]
> I removed Createpickupdan dump because of a kind of marker, but I couldn't add it with your help in this issue I think we can fix it please help.

Hello, i just uploaded new commit, where you now has 2 new options on config, you can set to appear as markers or pickups on drops. And thanks for your suggestion.
